<?php

$tender_req_en='';
$tender_req_ar='';
$termsandcondition_en='';
$termsandcondition_ar='';

$tender_req_en = <<<EOD
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Material Requirements:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">The material to be quoted must be exactly as specified in the 'Specification.' Alternatives may be accepted; however, all deviations from our specifications must be clearly stated otherwise they may be rejected. When the name of a particular manufacturer appears in the specification, you are to interpret this to mean the product of that manufacturer or its equivalent unless the manufacturer's product is shown as mandatory. If an equivalent is offered, your proposal must clearly state 'equivalent' and provide full descriptive technical data.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Please ensure that your bid includes full specification details and attach brochures, catalogues, etc. to facilitate evaluation of your bid.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Pricing:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Pricing should be in Qatari Riyals only. Items should be priced individually, extended according to quantity and then totaled. Any additional charges, incentives or discounts are to be shown separately. It should clearly state the total lump sum price of all components offered in the Format of Tender Form 'Annexure 1'.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Validity:<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Please confirm your quotation is valid for a period of 60 days.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Payment Terms:<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Net 60 days after completion of work, end user's approval/ satisfaction and submission of invoice.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Delivery:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Please state your best delivery/ lead time, allowing for anticipated holidays or any delays.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">If the Bidder (Contractor/ Supplier) fails to honor the 'Promised Delivery Schedule' stated in the bid, ALAQARIA may establish that damages have been caused to ALAQARIA, and exercise the right to impose 'Liquidated Damages' on the final invoice at the rate of maximum 10% of total order value.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Specifications:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">As per attached Schedule "B"</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Inspection:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Any order resulting from this enquiry shall be subject to inspection by ALAQARIA authorized representative. The presence of ALAQARIA representative shall not relieve the Successful Bidder from their own inspection and quality assurance responsibilities. It is a condition of purchase that the Successful Bidder submits, two weeks after receipt of any resulting PO, a Quality Control/ Inspection Plan.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Terms &amp; Conditions:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">The Successful Bidder will be issued a Purchase Order that will incorporate ALAQARIA's standard Terms &amp; Conditions of Purchase, copy of which is attached as Schedule "B." The Successful Bidder will be bound by these Terms &amp; Conditions and is deemed to have comprehended the same in preparing and submitting its quotation.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Bids are to be submitted on Bidder's company letterhead. Quotations must be in English and should be typewritten. Any mistakes made in completing of the tender and corrected before submission shall be initialed by the person authorized to sign the tender on behalf of bidder.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">ALAQARIA expressly retains the right to reject or accept any or all bids in whole or in part. ALAQARIA will not be responsible for any costs or expenses incurred by Bidder in connection with its preparation and submission of its tender.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Experience:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">As a condition of tendering for this requirement, you are required to submit a list of projects where you, your Principal, have manufactured and performed work of similar nature in the past five (5) years and the names of your customers along with the countries to which the goods were delivered.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">You are requested to state whether you or your manufacturer(s) is accredited to ISO 9001. If so, please state which ISO standard you have attained.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Other:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Failure to comply with any of our requirements, specifications or otherwise, may result in the rejection of your quotation.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Commercial and Technical Offers:</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Bidders are required to submit their quotations in One (1) wax sealed envelope.<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Document One: Commercial: Priced Offer that includes prices and terms and conditions governing delivery. It should clearly state the total lump sum price of all components offered.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">This One Envelope should be clearly marked and addressed as follows:<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Qatar Real Estate Investment Company<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Tender Committee<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Second Floor &nbsp;- Reception Desk<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Old Salata, Museum Street<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />P.O. Box 22311<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Doha, Qatar</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Tender No.:<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Bid Closing Date:<br style="margin: 0px; padding: 0px; border: 0px none;" /><br style="margin: 0px; padding: 0px; border: 0px none;" />Time:&nbsp;&nbsp;between 8:00 and 12:00 hours</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Failure to comply with the instructions above may result in the rejection of your quotation. Method of delivery shall be decided by you at your own risk; we recommend courier or hand delivery.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Correction of Arithmetical and/or other Errors</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Should the amount put in words differ from the amount put in figures, or if there is any arithmetical error in the Tender, the lesser amount shall be taken unless the discrepancy is attributable to an obvious error, whereupon the correct amount shall be taken.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Any adjustment, correction, clarification or amendment made by ALAQARIA to a Tender will be communicated to the Bidder for his acknowledgement prior to award of the contract.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">TENDERS RECEIVED AFTER THE BID CLOSING DATE AND TIME WILL NOT BE CONSIDERED.</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">If you have any questions concerning this enquiry, please contact the undersigned in writing on Fax +974 4443 1693</p>

EOD;

$tender_req_ar = <<<EOD

<h2 style="margin: 0px 0px 10px; padding: 0px; font-weight: 400; line-height: 24px; font-family: DauphinPlain; font-size: 24px; text-align: right;"><strong>ما هو "لوريم إيبسوم" ؟</strong></h2>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.</p>
<h2 style="margin: 0px 0px 10px; padding: 0px; font-weight: 400; line-height: 24px; font-family: DauphinPlain; font-size: 24px; text-align: right;"><strong>ما هو "لوريم إيبسوم" ؟</strong></h2>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.</p>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">&nbsp;</p>
<h2 style="margin: 0px 0px 10px; padding: 0px; font-weight: 400; line-height: 24px; font-family: DauphinPlain; font-size: 24px; text-align: right;"><strong>ما هو "لوريم إيبسوم" ؟</strong></h2>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.</p>

EOD;



// ----------------------Tender Terms and Conditions---------------------------------

$termsandcondition_en = <<<EOD
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Definitions</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">In addition to the terms defined in Article 1, the following definitions shall be used for the purpose of interpreting the Purchase Order:</p>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">The 'First Party' means Qatar Real Estate Investment Company (PURCHASER)</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">The 'Second Party' means (CONTRACTOR) named as such on the face of the Service Contract.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">"CONTRACTOR Personnel" shall mean all individuals, whether employees of CONTRACTOR or not, provided and/or engaged in the Services by the CONTRACTOR.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">"Party/Parties" shall mean in the singular either the Purchaser or CONTRACTOR and in the plural both the Purchaser and CONTRACTOR.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">"Services" shall mean those service specified in Scope of Services stated in the Contract Agreement or as can reasonably be implied there from.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">"Site" shall mean all the places within the State of Qatar as designated by the Purchaser where the Services are to be performed.</li>
</ol>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Contractor and Purchaser agree that:</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">Document containing the standard "Scope of Services" attached hereto and incorporated herein as Appendix A is an integral part of the Purchase Order.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">Document containing the standard "Table of Prices" attached hereto and incorporated herein as Appendix B is an integral part of the Purchase Order.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">Compensation for provision of the services shall be provided in the relevant page of the purchase order.</li>
</ol>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>The Services</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">Document stating the Scope of Services does not claim to include every detail and all specification for the Services. CONTRACTOR shall provide any additions and inclusions on a timely basis to the complete scope, specifications and details reasonably necessary to meet the overall intent and scope of the Services.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">The rates and prices included in the CONTRACTOR&rsquo;s invoices for the Services are inclusive of all costs, charges, taxes, duties and all other expenses for performing the Services.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall perform the Services with due diligence and efficiency and in accordance with good practices and accepted professional standards and meeting the intents and obligations outlined in and implied from the Alaqaria representative request for supply of service.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall be responsible for safety during the performance of the Services and shall provide all necessary safeguards to ensure the safety and protection of the Site and of all persons and property associated with the Services.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall notify the Purchaser immediately of any accidents, incidents, impeding or actual stoppages of work, industrial disputes or other matters which are likely to affect the performance of the Services, the interests or other operations of Purchaser or others.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall act as independent contractors with respect to the Services and neither CONTRACTOR nor its personnel or Sub-CONTRACTORs or their personnel shall be deemed to the agents or employees of Purchaser in the performance of the Services.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR agrees that it has satisfied itself as to the nature of the Services, the correctness and sufficiency of the rates and prices stated in the Purchase Order, general and local conditions of the Site and all other matters which could affect performance of the Services. Any failure by CONTRACTOR to take account of matters which affect the Services shall not relieve CONTRACTOR form its obligations under the Purchase Order.</li>
</ol>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>CONTRACTOR Personnel</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;">
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR warrants that the performance by CONTRACTOR Personnel shall comply with the ALAQARIA representative&rsquo;s request for supply of service and that they shall exercise the highest degree of care, skill and diligence in carrying out the Services as is expected of them as experts in the industry. CONTRACTOR further warrants that it shall continuously provide all necessary CONTRACTOR Personnel and shall ensure the CONTRACTOR Personnel are not replaced without the prior approval of Purchaser to a suitable successor.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR warrants that all CONTRACTOR Personnel have sufficient qualifications and experience to perform their tasks safely, competently, and efficiently, and shall ensure that they are healthy, fit and suitable in every respect to perform the Services. CONTRACTOR shall also ensure that all CONTRACTOR Personnel qualifications or experience levels meet or exceed any particular minimum standards or other requirements which are specified by Purchaser. CONTRACTOR shall supply Purchaser with evidence of the qualifications, training, and experience of CONTRACTOR Personnel, and shall promptly submit any detailed information which is required by Purchaser concerning CONTRACTOR Personnel in order to enable Purchaser to review the information and notify CONTRACTOR of approval/rejection.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">Purchaser may notify CONTRACTOR to remove from any location of Purchaser or from the Services any officer, employee or agent of either CONTRACTOR or any Sub-CONTRACTOR without offering any reason provided only that such right is not exercised unreasonably. The person shall be removed forthwith at the expense of CONTRACTOR and shall not be engaged on the Services again or on any other work of Purchaser without the prior approval of Purchaser. Persons who have been removed from the Services shall immediately be replaced, if Purchaser so requires, by other suitably qualified persons acceptable to Purchaser.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">Unless otherwise provided for in this agreement, CONTRACTOR shall, at its own cost, provide or arrange all travel, local transport, accommodation, food, all requirements for medical and dental attention, treatment, examination, care, hospitalization and/or ambulances or other medical transport and all necessary personal safety equipment and protective clothing for CONTRACTOR Personnel. Notwithstanding the forgoing, in emergency situations ALAQARIA may provide, at CONTRACTOR's sole risk and responsibility, medical assistance to CONTRACTORs Personnel and back charge CONTRACTOR for the cost.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall ensure that all CONTRACTOR Personnel undergo and medical examinations required by the State of Qatar or Purchaser and shall supply Purchaser with relevant details of medical and/or health records for CONTRACTOR Personnel if required to do so by Purchaser.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall provide Purchaser with photocopies of passports, police clearances and any similar personal security documentation necessary to obtain Purchaser identification cards and passes for CONTRACTOR Personnel. CONTRACTOR shall ensure that CONTRACTOR Personnel carry such identification cards with them at all times when they are at the Site or at any Purchaser&rsquo;s premises.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall require all CONTRACTOR Personnel to be law abiding, peaceful, and respectful of local cultural traditions.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall ensure that all CONTRACTOR Personnel have all necessary visas, sponsorship documentations, work permits, and other immigration requirements. CONTRACTOR shall be responsible for payment of any fees and/or charges for CONTRACTOR Personnel visa, sponsorship, work permit and similar documentation. If CONTRACTOR so requests, ALAQARIA will provide CONTRACTOR with reasonable assistance to secure the forgoing requirements and all provide CONTRACTOR with reasonable assistance to secure the forgoing requirements and all costs incurred by ALAQARIA in the provision of such assistance will be to the CONTRACTOR's account.</li>
</ol>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Materials and Equipment Provided by the CONTRACTOR</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Except where it is expressly provided that Purchaser shall provide an item of materials or equipment, CONTRACTOR shall provide all materials, equipment and all other things necessary for performance of the Services, so far as the necessity for providing the same is specified in or is reasonably to be inferred from the Purchase Order. Materials, tools and equipments or part thereof provided by CONTRACTOR for which there is no detailed specification included in the Purchase Order shall be fit for their intended purpose and of best quality and workmanship. CONTRACTOR shall be fully responsible for all repairs, maintenance, overhauling and servicing of all tools and equipment provided by CONTRACTOR.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Inspection of the Services</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">In order to confirm that the requirements of the ALAQARIA representative&rsquo;s request are met, Purchaser shall have the right, but not the obligation, at all time to inspect, test and examine all the Services.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">Purchaser shall have the right to reject any part of the Services which does not comply with any requirement or requirements of the Purchase Order. Upon receiving notice of rejection CONTRACTOR shall immediately commence to re-perform, repair or replace the defective part of the Services and shall carry out such inspections and/or tests on other parts of the Services as Purchaser may require to ensure that there are no similar parts of the Services that fail to comply with the requirements of the Purchase Order.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall be responsible for all costs and delays relating to re-performance, repair, replacement, uncovering, reinstating, testing and inspection.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">Neither failure on the part of Purchaser or its designated inspectors to inspect the Services or witness or test or to discover defects nor failure to reject work performed by CONTRACTOR or a Sub-CONTRACTOR which is not in accordance with the Purchase Order shall relieve the Seller from any responsibility of complying to the scope of work stated in the face of the contract.</li>
</ol>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Guarantee of the Services</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR guarantee that the Services shall be free from errors, defects and failures for the same guarantee period for the Work as stated in the Purchase Order.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">In the event of any breach of Article 6.0 above, CONTRACTOR shall immediately at its own cost, rectify, or at the Purchaser's option replace or re-perform any defective work, and carry out all associated work such as re-preparation and presentation of documents/reports. Alternatively Purchaser may decide at its absolute discretion that the carrying out of such rectification by CONTRACTOR will be prejudicial to Purchaser's interests (whether by deferment of production or otherwise). In such circumstances Purchaser may undertake CONTRACTOR's above mentioned responsibilities, in which event Purchaser shall, as soon as reasonably practicable, so notify CONTRACTOR. Purchaser shall be entitled to recover from CONTRACTOR all costs incurred by Purchaser in correcting such error, defect or failure.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">The rights and remedies of Purchaser provided under this Article are without prejudice to Purchaser's other rights or remedies under the Purchase Order and/or at law.</li>
</ol>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Liabilities and Indemnities Related to the Services</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">CONTRACTOR shall release, protect, indemnify, defend and hold harmless the Purchaser, its affiliates, its joint venture partners and their respective officers, employees and agents:<br style="margin: 0px; padding: 0px; border: 0px none;" />
<ol style="border: 0px none; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="i">
<li style="margin: 0px; padding: 0px; border: 0px none;">in respect of loss of or damage to the property, facilities, material, equipment, tools, owned or rented, which are provided by CONTRACTOR, its Sub-CONTRACTORs or their respective officers, employees, agents or by CONTRACTOR Personnel for use or intended for use in the performance of the Services, and</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">from all claims losses, damages, costs (including legal costs), expenses and liabilities of every kind and nature resulting from personal injury, including fatal injury and disease, to any person employed by CONTRACTOR or its Sub-CONTRACTORs including CONTRACTOR Personnel arising directly or indirectly out of or in connection with the performance of the Purchase Order.</li>
</ol>
</li>
</ol>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Without regard to the cause or caused thereof, including, without limitation, the fault of negligence (whether sole, concurrent, active, passive or otherwise) or breach of duty (statutory, contractual or otherwise) of either Party or any other person or entity.</p>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" start="2" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">The obligations of the Parties with respect to injury to third parties or damage to the property of third parties shall be as follows:<br style="margin: 0px; padding: 0px; border: 0px none;" />
<ol style="border: 0px none; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="i">
<li style="margin: 0px; padding: 0px; border: 0px none;">subject to Article 7.0 (a) above, CONTRACTOR shall release, protect, indemnify, defend and hold harmless the Purchaser, its affiliates, its joint venture partners and their respective officers, employees and agents in respect of all claims, losses, damages, costs (including legal costs), expenses and liabilities of every kind and nature resulting from:</li>
</ol>
</li>
</ol>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;">
<li style="margin: 0px; padding: 0px; border: 0px none;">personal injury, including fatal injury and disease of any third party and/or</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">any loss of or damage to the property of any third party,</li>
</ol>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">arising directly/or indirectly out of or in connection with the performance of the Purchase Order without regard to the cause or causes thereof, including without limitation, the fault or negligence (whether sole, concurrent, active, passive or otherwise) or breach of duty (statutory, contractual or otherwise) of either Party or any other person or entity.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Insurance</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">During the period that CONTRACTOR is performing the Services and throughout the Guarantee Period, CONTRACTOR shall provide and maintain an insurance to cover Contractor&rsquo;s operation and equipment.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Miscellaneous</strong></h3>
<ol style="border: 0px none; color: #333333; font-family: Arial, sans-serif; font-size: 12px; padding: 0px 0px 0px 40px !important; margin: 0px 0px 30px !important 0px;" type="a">
<li style="margin: 0px; padding: 0px; border: 0px none;">For any Services performed, CONTRACTOR and Sub-CONTRACTORs shall keep accurate accounts and records showing all costs and charges incurred in accordance with generally accepted accounting principles and practices. The Purchaser or its authorized representative or agents shall have the right to examine, during business hours, all books, record, accounts, correspondence, instructions, receipts and memoranda of CONTRACTOR and its Sub-CONTRACTOR insofar as they are pertinent to Services. CONTRACTOR shall be responsible for ensuring that all of its and its Sub-Contractors&rsquo; documentation is preserved and made available at any time for audit, without any additional compensation thereof, any time during the currency of the Purchase Order and up to five years from the date the Services are completed.</li>
<li style="margin: 0px; padding: 0px; border: 0px none;">For any dispute or controversy concerning the Services which cannot be settled by agreement between the Parties, the Parties agree to submit to the exclusive jurisdiction of the courts of Qatar as the proper legal venue.</li>
</ol>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">CONTRACTOR shall abide by and comply, and secure compliance by its Sub-CONTRACTOR&rsquo;s with, and shall obtain all licenses, permits, temporary permits and authorizations required by, any and all applicable laws, rules and regulations of any governmental or regulatory body having jurisdiction over the Services.</p>
<h3 style="margin: 0px 0px 20px; padding: 0px; border: 0px none; font-size: 15px; text-align: justify; color: #333333; font-family: Arial, sans-serif;"><strong>Payment Terms</strong></h3>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">30 days after receipt of CONTRACTOR&rsquo;s invoice and end user&rsquo;s Acknowledgement of Receipt of Materials.&nbsp;</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">It is important, in order to avoid payment delays, that your invoice together with its supporting documents (including end user's approval on the completion of work) is dispatched/ handed over to:</p>
<p style="margin: 0px 0px 20px; padding: 0px; border: 0px none; text-align: justify; color: #333333; font-family: Arial, sans-serif; font-size: 12px;">Qatar Real Estate Investment Company<br style="margin: 0px; padding: 0px; border: 0px none;" />Finance Department<br style="margin: 0px; padding: 0px; border: 0px none;" />2nd Floor of Qatar International Islamic Bank<br style="margin: 0px; padding: 0px; border: 0px none;" />Kahraba Street<br style="margin: 0px; padding: 0px; border: 0px none;" />P.O. Box 22311<br style="margin: 0px; padding: 0px; border: 0px none;" />Doha, Qatar</p>
EOD;

$termsandcondition_ar = <<<EOD
<h2 style="margin: 0px 0px 10px; padding: 0px; font-weight: 400; line-height: 24px; font-family: DauphinPlain; font-size: 24px; text-align: right;"><strong>ما هو "لوريم إيبسوم" ؟</strong></h2>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.</p>
<h2 style="margin: 0px 0px 10px; padding: 0px; font-weight: 400; line-height: 24px; font-family: DauphinPlain; font-size: 24px; text-align: right;"><strong>ما هو "لوريم إيبسوم" ؟</strong></h2>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.</p>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">&nbsp;</p>
<h2 style="margin: 0px 0px 10px; padding: 0px; font-weight: 400; line-height: 24px; font-family: DauphinPlain; font-size: 24px; text-align: right;"><strong>ما هو "لوريم إيبسوم" ؟</strong></h2>
<p dir="rtl" style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: 'Open Sans', Arial, sans-serif;">لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.</p>

EOD;








?>